services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama-local:/root/.ollama
    ports:
      - 11434:11434
  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui-local:/app/backend/data

volumes:
  ollama-local:
    external: true
  open-webui-local:
    external: true